// Author: cbm-hackers
// JumpJumpJump
// https://crackmes.one/crackme/5c1a939633c5d41e58e005d1

// Solution by Yuri:
/* This crackme loops through a string, adds all the ascii characters including
null byte, and compares against a hard coded value of 0x3E8.

I used the ascii value n 9 times.
(0x6E * 9) + 0xA = 0x3E8

The flag is generated using the strcat_str() function, which writes the flag to a global
char array. The function starts with an '!' value, and then uses that character to generate the next
character in the array. It does this by taking the value, adding it by the value, and adding 1 to that value.
The third value is generated by the second, and the fourth is generated by the third, and so on.

*/

//	[user@comp ~/crackmes.one/jumpjumpjump]# ./rev03 
//	enter the magic string
//	nnnnnnnnn
//	flag is flag{!#&*/5<DMW}


// The hardcoded value of 0x3E8 was located at 00101269

//        00101264 48 39 c3        CMP        RBX,RAX
//        00101267 72 cf           JC         LAB_00101238
//        00101269 81 7d ec        CMP        dword ptr [RBP + asciiSum],0x3e8
//                 e8 03 00 00
//        00101270 75 5f           JNZ        LAB_001012d1
//        00101272 b8 00 00        MOV        EAX,0x0
//                 00 00


// Program was decompiled using Ghidra


#include <stdio.h>
#include <string.h>

char flag[10];
char inputString[64];

/* char *strcat_str() {
	flag[0] = '!';
	int counter = 1;
	while (counter < 10) {
		flag[counter] = flag[counter-1] + counter + 1;
		counter++;
	}	
	return flag;
}
 */

char *strcat_str() {
  int counter;
  
  flag[0] = '!';
  for (counter = 1; counter < 10; counter++) {
	    //(flag)[counter] = (char)counter + (flag)[counter + -1] + 1;
		flag[counter] = flag[counter-1] + counter + 1;
  }
  return flag;
}

int main() {
	int asciiSum = 0;
	puts("enter the magic string");
	fgets(inputString, 64, stdin);
	if (strlen(inputString) >= 11) {
		puts("too long...sorry no flag for you!!!");
	} else {
		int counter = 0;
		while (counter < strlen(inputString)) {
			asciiSum += inputString[counter];
			counter++;
		}
		if (asciiSum == 1000) {
			strcat_str();
			printf("flag is flag{");
      		for (counter = 0; counter < 10; counter++) {
        		putchar((int)*(char *)(flag + counter));


/* Using for statement:

 			int count = 0;
			while (count < 10) {
				putchar(flag[count]);
				count++; */
			}
			puts("}");
		} else {
			puts("wrong string\nNo flag for you.");
		}
	}
}